name: Deploy binary
on:
  create:
    tags:
      - v*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.10.1+musl+static+flambda

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Build
        run: |
          sudo apt-get install musl-tools
          opam install dune containers fmt fileutils cmdliner timere
          opam pin add timere-parse https://github.com/daypack-dev/timere.git
          eval $(opam env); make
          cp _build/default/src/dirsift.exe dirsift
      - name: Upload to GitHub release
        uses: actions/upload-artifact@v2-preview
        with:
          name: dirsift
          path: dirsift
